### ISSUE TITLE
关于mina长连接

### ISSUE THREAD

**Issue by cyq7on** [yipianfengye/androidProject#1]
创建后台服务，在服务中创建MINA长连接；
实现长连接断了之后的重连机制，并且重连次数有限制不能一直重连；
您好，以上是您文中提到的两个流程，重连次数为什么有限制呢？如果没有限制，是否可以省略后台服务，单独依靠后者进行重连？

**Comment by yipianfengye** [comment]
重连接次数有限制的，大概是可以重连接10次，这里的重新连接通过代码重新连接，十次之后还有每个一分钟的闹钟服务检测长连接状态，若没有连接的话也会重新执行连接操作。
另外在长连接断开之后会启动一个轮训服务，当长连接恢复之后关闭轮训服务，这样可以保证消息的及时性。

**Comment by cyq7on** [comment]
好的，O(∩_∩)O谢谢

**Comment by yipianfengye** [comment]
O(∩_∩)O哈哈~，共同学习

**Comment by ygbingo** [comment]
赞
